server:
  port: 8080

spring:
  profiles:
    include:
      - jwt
      - oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[show_sql]": true
  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  file:
    path: logs
  level:
    root: error
    com:
      fyo: info