server:
  port: 8080

spring:
  profiles:
    include:
      - jwt
      - oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true

logging:
  file:
    path: logs
  level:
    com:
      fyo: info